name: docker

on:
  workflow_dispatch: 
    inputs:
      Version:
        type: string 
        required: true
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      BUILD_CONFIGURATION: Release
      
    steps:      
# ------------------------------------------------------------------------------------------------------
# Copy Ginger repo
# ------------------------------------------------------------------------------------------------------
      - uses: actions/checkout@v3

# ------------------------------------------------------------------------------------------------------
# Build Docker && Release it to Packages
# ------------------------------------------------------------------------------------------------------    
      - name: Log in to the Container registry
        run: | 
          docker build -t ginger:${{github.event.inputs.Version}} .
        
      - name: Log in to the Container registry
        run: | 
          docker images
          
          
      - name: Log in to the Container registry
        run: | 
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
          
      - name: Log in to the Container registry
        run: | 
          docker push ginger:123.123.123


#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#           tags: |
#             type=semver,pattern={{version}},value=${{github.event.inputs.Version}}
#       - name: Build and push Docker image
#         uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
