name: dockerdemo

on:
  workflow_dispatch: 
    inputs:
      Version:
        type: string 
        required: true
  workflow_call:
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Deploy
    permissions:
      contents: read
      packages: write
    
    env:
      BUILD_CONFIGURATION: Release
      
    steps: 
      - uses: actions/checkout@v3

      - name: Change gingerRuntime files to be Execuable 
        run: | 
          find ./Runtime -type f -print0 | xargs -0 chmod +x


# ------------------------------------------------------------------------------------------------------
# Log in to the Container registry - GHCR
# ------------------------------------------------------------------------------------------------------

      - name: Log in to the Container registry - GHCR
        run: | 
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
# ------------------------------------------------------------------------------------------------------
# Create GingerRuntime docker image
# ------------------------------------------------------------------------------------------------------
      - name: Building GingerRuntime docker image
        run: |
          docker build -t gingerruntime .
        
      - name: Change image tag to be pushed for GHCR
        run: |
          docker tag gingerruntime ghcr.io/${{ github.actor }}/gingerruntime:latest
          
      - name: Pushing GingerRuntime Image
        run: | 
          docker push ghcr.io/${{ github.actor }}/gingerruntime:latest

