name: docker

on:
  workflow_dispatch: 
    inputs:
      Version:
        type: string 
        required: true
      major:
        type: number 
        required: true
        default: '23'
      minor:
        type: number 
        required: true
        default: '1'
      build:
        type: number 
        required: true
        default: '0'
      revision:
        type: number 
        required: true
        default: '0'
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VER: 2023.1-Alpha 1.1
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      BUILD_CONFIGURATION: Release
      
    steps:      
# ------------------------------------------------------------------------------------------------------
# Copy Ginger repo
# ------------------------------------------------------------------------------------------------------
#       - uses: actions/checkout@v3

# ------------------------------------------------------------------------------------------------------
# Build Docker && Release it to Packages
# ------------------------------------------------------------------------------------------------------    
#       - name: Log in to the Container registry
#         run: | 
#           docker build -t ginger .
        
#       - name: Log in to the Container registry
#         run: |
#           docker tag ginger ghcr.io/${{ github.actor }}/ginger:${{github.event.inputs.Version}}
#           docker images 
          
          
#       - name: Log in to the Container registry
#         run: | 
#           docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
          
#       - name: Log in to the Container registry
#         run: | 
#           docker push ghcr.io/${{ github.actor }}/ginger:${{github.event.inputs.Version}}


      - name: Update environment variable value
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |
          echo $VER
          echo "::set-env name=VER::2023.1-Alpha 0.1"
          echo $VER
          
      - name: Update environment variable value1
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |          
          echo ${{ env.GINGERVER }}
          echo "::set-env name=env.GINGERVER::2023.1-Alpha 1.1"
          
      - name: print ${{github.event.inputs.Version}}
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: 'true'
        run: |          
          echo ${{github.event.inputs.Version}}
          
      - name: create version environment variable
        if: ${{ github.event.inputs.revision != 0 }}
        run: |
          echo "yes it is"
          
      - name: create version environment variable
        if: ${{ github.event.inputs.revision == 0 }}
        run: |
          echo "yes it is"

#       - name: Extract metadata (tags, labels) for Docker
#         id: meta
#         uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
#         with:
#           images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#           tags: |
#             type=semver,pattern={{version}},value=${{github.event.inputs.Version}}
#       - name: Build and push Docker image
#         uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
#         with:
#           context: .
#           push: true
#           tags: ${{ steps.meta.outputs.tags }}
#           labels: ${{ steps.meta.outputs.labels }}
