name: docker

on:
  workflow_dispatch: 
    inputs:
      Version:
        type: string 
        required: true
      major:
        type: number 
        required: true
        default: '23'
      minor:
        type: number 
        required: true
        default: '1'
      build:
        type: number 
        required: true
        default: '0'
      revision:
        type: number 
        required: true
        default: '0'
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VER: 2023.1-Alpha1.1
  
jobs:

  my-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Code Checkout 
        uses: actions/checkout@v3
        
# ------------------------------------------------------------------------------------------------------
# Log in to the Container registry - GHCR
# ------------------------------------------------------------------------------------------------------

      - name: Log in to the Container registry - GHCR
        run: | 
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} 
# ------------------------------------------------------------------------------------------------------
# Create GingerRuntime docker image
# ------------------------------------------------------------------------------------------------------
      - name: Building GingerRuntime docker image
        run: |
          docker build -t gingerruntime .
        
      - name: Change image tag to be pushed for GHCR
        run: |
          docker tag gingerruntime ghcr.io/${{ github.actor }}/gingerruntime:"${{ env.VER}}"
          
      - name: Pushing GingerRuntime Image
        run: | 
          docker push ghcr.io/${{ github.actor }}/gingerruntime:"${{ env.VER}}"

      - name: Change image tag(latest) to be pushed for GHCR
        run: |
          docker tag gingerruntime ghcr.io/${{ github.actor }}/gingerruntime:latest
          
      - name: Pushing GingerRuntime Image
        run: | 
          docker push ghcr.io/${{ github.actor }}/gingerruntime:latest

# ------------------------------------------------------------------------------------------------------
# Create GingerRuntime with Browsers docker image
# ------------------------------------------------------------------------------------------------------
      # - name: Building gingerruntime-browsers docker image
      #   run: |
      #     cd Ginger/GingerRuntime/Containers/Browsers
      #     docker build -t gingerruntime-browsers .
        
      # - name: Change image tag to be pushed for GHCR
      #   run: |
      #     docker tag gingerruntime-browsers ghcr.io/${{ github.actor }}/gingerruntime-browsers:"${{ env.gingertag}}"
          
      # - name: Pushing gingerruntime-browsers Image
      #   run: | 
      #     docker push ghcr.io/${{ github.actor }}/gingerruntime-browsers:"${{ env.gingertag}}"

      # - name: Change image tag(latest) to be pushed for GHCR
      #   run: |
      #     docker tag gingerruntime-browsers ghcr.io/${{ github.actor }}/gingerruntime-browsers:latest
          
      # - name: Pushing gingerruntime-browsers Image
      #   run: | 
      #     docker push ghcr.io/${{ github.actor }}/gingerruntime-browsers:latest
