name: habal

on:
  workflow_dispatch: 
    inputs:
      Version:
        type: string 
        required: true
      major:
        type: number 
        required: true
        default: '23'
      minor:
        type: number 
        required: true
        default: '1'
      build:
        type: number 
        required: true
        default: '0'
      revision:
        type: number 
        required: true
        default: '0'
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  VER: 2023.1-Alpha1.1
  
jobs:

  my-job:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Code Checkout 
        uses: actions/checkout@v3

      - name: dwonload exe from URL
        run: |
          wget https://github.com/Ginger-Automation/Ginger/releases/download/untagged-fbb5e6f8b70f99886709/Ginger.2023.13-Official.exe
# ------------------------------------------------------------------------------------------------------
# Log in to the Container registry - GHCR
# ------------------------------------------------------------------------------------------------------

      - name: Log in to the Container registry - GHCR
        run: | 
          ls -altr
   
