name: dockerdemo

on:
  workflow_dispatch: 
    inputs:
      Major:
        type: string 
        required: true
   
      Minor:
        type: string 
        required: true
        
      build:
        type: string 
        required: true
        default: '0'
        
      revision:
        type: string 
        required: true
        default: '0'
        
  workflow_call:
#     inputs:
#       Version:
#         type: string 
#         required: true
  
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    env:
      BUILD_CONFIGURATION: Release
      
    steps:      
      - uses: actions/checkout@v3
        with:
            ref: 'Document1'
      
      - name: print
        run: |
          ls -alt
