name: Deploy

on:
    workflow_dispatch: 
    
    workflow_call:

jobs:
    Deploy-Project:
      name: Deploy Releases to Github Release
      runs-on: ubuntu-latest
      steps:         
# ------------------------------------------------------------------------------------------------------
# Copy Ginger repo
# ------------------------------------------------------------------------------------------------------
          - uses: actions/checkout@v3

          - name: Print content
            run: |
                ls -altr

# ------------------------------------------------------------------------------------------------------
# Create new Release for ginger
# ------------------------------------------------------------------------------------------------------

          - name: Recreate Release
            uses: GongT/actions-recreate-release@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              tag_name: v2.2.3
              release_name: Release v2.2.3
              draft: true
              prerelease: false

              
          # - name: Create Github new Release
          #   id: create-new-release
          #   uses: actions/create-release@v1
          #   env:
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
          #   with:
          #     tag_name: v2.2.3
          #     release_name: Release v2.2.3
          #     draft: true



# ------------------------------------------------------------------------------------------------------
# Upload Ginger Documents to Github Releases 
# ------------------------------------------------------------------------------------------------------
          - name: Upload Assest to Github Releases - Ginger.Release.Notes.pdf
            if: ( !(contains(env.gingertag , 'Beta' )) && !(contains(env.gingertag , 'Alpha' )) )
            uses: actions/upload-release-asset@v1
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              upload_url: ${{ steps.create-new-release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
              asset_path: ./Ginger.Release.Notes.pdf
              asset_name: Ginger.Release.Notes.pdf
              asset_content_type: application/doc
